name: Loan_prediction
channels:
  - defaults

dependencies:
  - python=3.9.19
  - pip<=24.2
  - pip:
    - mlflow==2.13.0
    - cloudpickle==2.2.1
    - importlib-metadata==7.0.0
    - jaraco-classes==3.3.0
    - jaraco-context==5.3.0
    - jaraco-functools==4.0.1
    - jaraco-itertools==6.4.1
    - jaraco-text==3.12.1
    - more-itertools==10.2.0
    - numpy==1.26.3
    - ordered-set==4.1.0
    - packaging==24.1
    - psutil==5.9.4
    - pyyaml==6.0.1
    - scikit-learn==1.5.0
    - scipy==1.13.1